# Generated by Django 6.0 on 2025-12-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_user_email_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
